### PR TITLE
Speedup

### PR DESCRIPTION
**Pull request by gpgreen**
This is a large change. I wanted to speed up the loading of Grib files, as it took many minutes on my computer. I created a new class "GribFile", that loads the grib file into memory and also counts the records. Once that is done, a new class instance of "GribRecordBuffer" is created on each record found in the grib file. Then these instances are included in an instance of "GribRecordTask", which is a QRunnable. These are then loaded into the QThreadPool, where each is run and the resulting GribRecord or Grib2Records are collected.

The result is a substantial speedup. The grib file i was using would
take nearly 10 minutes to load. With this change it is about 2
seconds. I didn't do timing as the speedup was so large.

Finally I don't have a windows or macosx development environment, so
this was only tested on linux with ubuntu 20.04.

### CODE REVIEW

**Comment by norulz** [comment]
Thanks Greg,
Will examine the PR in the next release.
David

**Comment by norulz** [comment]
Hi @did-g ,
Can you please check this PR.
The loading of grib1 files with bz2 compression is indeed exceptionally slow in the Master branch. This was not so in version 1.2.6.
This leads me to think that we only need see what changed and perhaps only revert to previous code. Is this huge change necessary?

**Comment by did-g** [comment]
Ok, I'm looking at  it.

**Comment by did-g** [comment]
Hi,

1863f99ba6f082249241227191b74a4f6a098c0a is the culprit. Trying to open it as grib2 first as a bad idea. I'm looking at it.

Regards
Didier

**Comment by norulz** [comment]
The issue has been resolved by reverting a recent change to the file loading that was causing the slow opening of bz2 compressed files.
Thanks

**Pull request closed without merging**
