### PR TITLE
WIP If no MSL pressure use SFC pressure if available

### PR DESCRIPTION
**Pull request by did-g**
Hi,

Arome Meteo France 0.01 has only surface pressure not mean sea level. 
Display it but not as a fake MSL. 
They have an altitude grib available so computing MSL from surface should be doable though (with a 12 hours lag for temperature?).
You can get some pre-cut sample at: 
http://176.31.74.196/OPENGRIBS/
(I mask pressure over land) 

There's still a couple of misleading MSL (menu and values panel), If we decide commit this one, I'll fix them first.

Regards
Didier

### CODE REVIEW

**Comment by norulz** [comment]
I'm a bit worried about this one.

PRES sfc is used in skew-t data requests for GFS, Arpege and ICON and the data at sfc (not corrected to msl) is needed in its native values. 
What will happen if the user does not request PRMSL or PRES msl (which is normalized)? Will the PRES sfc be used to represent PRES msl? Could it affect the skew-t calculations?

**Comment by dominiquehausser** [comment]
Just to well understand.
PRES msl  equivalent PRMSL (QNH)
PRES sfc (QFE)

At sea, they should be nearly the same, on land difference increase with altitude.
As XyGrib is the most sophisticated grib vizualizer targetting sailors but also pilots of flying engines and many others, I would say we could allow to explicitly download these 2 different values.

I understand, that is a relatively big job on variable definitions, but as soon as there is work to set multiple slots, there will be a big job on varialbes, why not link this with the more general work on slots ?

**Comment by norulz** [comment]
Hi @did-g and @dominiquehausser 

I gave this issue more thought and I'm against creating a PRMSL equivalent on the fly inside XyGrib for a model that does not publish PRMSL or PRESS @ msl (which are the same thing! Some use the first and some producers use the second). 

There is probably a good reason why MF do not include PRESS @ msl in the 1km gribs as there is a tendency at these resolutions to have hysteresis of the isobars mainly following terrain. This makes it difficult to see any synoptic patterns clearly which is the main purpose of PRMSL.

To show this please load the openWRF 1km Grib for Israel (on the openSkiron.org site) and see what happens to isobars on very high resolution gribs (try 2mb and 1mb spacing)

There is little value in PRESS @ sfc on its own. It does not tell us much except an approximation of terrain altitudes. It is used in calculating secondary values mainly associated with convection and stability. In XyGrib it is needed for Skew-t calculations

I suggest that when a variable is not included at all in a model's output and there is a need to have it, the variable should be created in pre-processing of the Gribs. To do PRMSL on the fly one would need to load variables needed for the calculation alone. Variables that would not be displayed or used otherwise. In high resolution gribs this is quite a penalty. (Height and TMP sfc come to mind)

I know that we have at least one exception to this, DPT (dew point temperature) which we create on the fly during loading if it does not exist. However, this is a trivial calculation and RH and TMP 2m are usable variables and not overhead.

How important is it to create PRMSL for the Arome 0.01 deg gribs?

Cheers for reading up to here :-)
David

**Comment by did-g** [comment]
Ok
>There is probably a good reason why MF do not include PRESS @ msl in the
1km gribs as there is a tendency at these resolutions to have hysteresis of
the isobars mainly following terrain. This makes it difficult to see any
synoptic patterns clearly which is the main purpose of PRMSL.
Agree, it's the reason why I mask it over land (using MF mask) and only
keep water , should remove lac Léman though...

> How important is it to create PRMSL for the Arome 0.01 deg gribs?
I don't think we need PRMSL but be able to display Pressure would be great
for data validation.
MF 0.01 is for local events but if they can't predict the past the future
ain't be any good.
MF data is available roughly four hours late and ideally with a reasonably
good barometer or airport it'd be possible to double check these four hours.

**Comment by norulz** [comment]
If PRESS sfc is used in MF 0.01 as you describe, I don't have a problem. The fact that the pressure shown is not normalized to msl (QNH) but rather the pressure at the surface altitude (QFE) needs to be clear in the display / units etc.

We do need to be careful in GFS, ICON global and Arpege global as these will include PRESS sfc in some cases (skew-t data requests). In these cases:

- The user has the decision to request and/or to display PRMSL (or PRESS msl). We should not then popup with PRESS sfc if it is loaded in these models' gribs as confusion will occur as PRESS sfc was not explicitly requested.
- No processing or 'translation' of PRESS sfc must occur when PRESS sfc might be used for skew-t

**Comment by did-g** [comment]
Ok, so
1) if there''s only >Surface should me display it in place of MSL with a
proper label by default? That's what the current patch do, without proper
label every

2) Create a new submenu MSL, SFL?

3) Only create a sub menu if both are present?

4) do nothing?

**Comment by dominiquehausser** [comment]
4) do nothing is what give less work ;-) and clearly QNH is the most useful value to estimate evolution. and may be the best solution.

1) If this what the patch do it means, that there is the need of have correct labels (with correct translations).

QFE allow you to verify that your barometer give you the correct info, but for that I get the data from the nearest observation station to calibrate and QFF is nearly only useful to calibrate your altimeter.
Personally, I would prefer to know which are the available variable and decide what I choose to download according to what I want to do (PRES msl and PRES sfc).

**Comment by norulz** [comment]
I'm for option 4) Do nothing. (on the  issue of PRESS sfc) :-)

**Comment by norulz** [comment]
I feel that a variable worth enhancing is precipitation.
There is interest to have precipitation total accumulation for a selected period.
i.e. "How much rain is forecast for a given point in the next 6h/12h/24h/'end of forecast' ?"
Windy's web site now includes this.
I reference and open issue for this #159

**Comment by did-g** [comment]
Hi,
Ok for 4) do nothing

Closing it 
Regards
Didier

**Pull request closed without merging**
