### PR TITLE
FIX error in version

### PR DESCRIPTION
**Pull request by theeko74**
By the way: GRIB server still does not work on my side...

capture d ecran 2018-06-09 a 18 11 58

### CODE REVIEW

**Comment by norulz** [comment]
Hi theeko74,

I have been working on the grib download dialog and on the grib server in the last 48 hours.
It is now stable with my last commits
I have returned the version number to 1.0.99 for beta release. Thus we can keep 1.1.0 for the actual release of the new version.
Thanks,
David

**Comment by theeko74** [comment]
Hi David,
The problem I have is that any time I open XyGrib from Qt, I got the message dialog which says that there is a new version to download... That's why I propose to use the latest version in the code, so we don't get this message every time.

**Comment by theeko74** [comment]
GRIB server is working, thanks !

**Comment by norulz** [comment]
Hi theeko74,
The "New Version" Info box is a new feature and it has been triggered for testing purposes only!
Please remember that the Master branch is under development and not yet branched for release.

**Comment by norulz** [comment]
Theeko74.... as I mentioned it was under testing. If you don't activate it - you can't test it!
Please have some patience.

**Pull request closed without merging**
