### PR TITLE
Noaa accumulation records

### PR DESCRIPTION
**Pull request by did-g**
Hi,
- regression from my previous patch
- map GRIB 2 hourly time to GRIB 1 
- convert average rate to accumulation for NOAA so 0-3, 0-6 kind of average works.

I have tested fast moving rain (last week hurricane offshore US East coast )  with
GRIB1 saildoc and zygrib data,
GRIB2 from xygrib and from NOAA subsetter (hourly 0.25 and three hours 0.5 steps) for _RATE and _TOT, seems to be ok

Regards
Didier

### CODE REVIEW

**Comment by norulz** [comment]
@did-g hi,
I have not yet been able to dig deep into these PRs and have one concern:
The new XyGrib on-demand server hosted on opengribs does normalize the GFS precipitation accumulation before the data is loaded for distribution. (Using wgrib2 -ncep_norm). This fixes the accumulation to 3hrs for each forecast step.

Should GFS gribs from other sources be loaded they may or may not retain the original GFS accumulation scheme.

Does your adaptation take this into account?

Cheers,
David

**Comment by norulz** [comment]
@did-g hi, can you please mail me at sy.wild.silk@gmail.com. Thanks, David

**Comment by norulz** [comment]
@did-g 
Hi there!
There are still some issues with the changes to precipitation accumulation.
When trying AROME 0.025 SP1 Gribs ([see at this link](https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=131&id_rubrique=51)) there is a problem with TPRATE.

The accumulation in the gribs is from start of forecast i.e. 0-1, 0-2, 0-3... and this can be seen in XyGrib. However the values are much much too high and appear to be a multiplication of 3600 which should not have been applied.

Second problem is that the accumulation is not normalized (i.e 0-1, 1-2, 2-3...) to maintain the presentation of precipitation as mm/hr.

If you have some free time, please take a look at this.

Regards,
David

**Comment by did-g** [comment]
Hi,
For AROME grib data look like an accumulation but it's defined as a rate.

Could you test https://github.com/opengribs/XyGrib/pull/84

Worth asking MeteoFrance if it's a mistake in param number.

Regards
Didier

**Comment by norulz** [comment]
ICON, Arpege, Arome and I believe ECMWF use TPRATE (parameter 52) but accumulate it keeping the rate descriptor. This article sheds some light on the issue [https://www.wmo.int/pages/prog/www/ISS/Meetings/IPET-DRC_Brasilia2010/Documents/IPETDRC-II_Doc2-3_13.doc](https://www.wmo.int/pages/prog/www/ISS/Meetings/IPET-DRC_Brasilia2010/Documents/IPETDRC-II_Doc2-3_13.doc).

Also look at NOAA table at [this link](http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-0-1.shtml) and look at the 3 stars note at the bottom (***).

DWD and Meteo France accumulate from start of forecast.

I feel that XyGrib should keep one representation of precipitation - rate per  hour and do all the required translation and normalization whatever the input parameter happens to be.

BTW I pre-normalize the ICON precipitation in the grib server and change it from TPRATE accumulated from start of forecast to APCP (param 8). Perhaps I can stop doing this as XyGrib now normalizes TPRATE itself.

David

**Comment by did-g** [comment]
Hi,
Good catch with the meeting proceeding, that's the issue.
I'm looking at a proper way to deal with it.

For testing have you some TPRATE ICON data available?

I'm not a big fan of rewriting GRIB but if it makes them more compatible
with other grib reader why not.

Regards
Didier

**Comment by norulz** [comment]
Here is some ICON TPRATE
[https://www.dropbox.com/sh/2jjoshm9zh4ds1p/AAA5F34ck1-C5u-Wu1j0dMXia?dl=0](https://www.dropbox.com/sh/2jjoshm9zh4ds1p/AAA5F34ck1-C5u-Wu1j0dMXia?dl=0)

I tried it in 1.1.1 and it is well normalized. In version 1.1.0 you can see the accumulation from start of forecast

**Pull request merged**
