### PR TITLE
Gust absolute

### PR DESCRIPTION
**Pull request by did-g**
Hi,
Add a display absolute gust speed mode,
Not sure it's the right menu though. Could be the default display too.

Regards
Didier

### CODE REVIEW

**Comment by dominiquehausser** [comment]
That's very nice.
For me, it only work with GFS and NAM CONUS model, not with Arpege and ICON (the same for relative gust visualisation), the other models have no gust data.

**Comment by did-g** [comment]
On Mon, Dec 31, 2018 at 10:35 AM Dominique Hausser <notifications@github.com>
wrote:

> That's very nice.
> For me, it only work with GFS and NAM CONUS model, not with Arpege and
> ICON (the same for relative gust visualisation), the other models have no
> gust data.
>
My bad, I haven't  tested it.
I'm looking at it, likely an issue with level ie, 0 vs 10 meter.

Have fun.
Didier

**Comment by norulz** [comment]
Hi @did-g 
Great job!
I made some minor adjustments and additions:
- Made absolute gusts the default
- Modified the map legend to show absolute or relative gusts
- Proofed the menu label gust -> gusts
- Added transparent values to CAPE, Reflectivity and Snow depth.

HAPPY NEW YEAR

**Comment by dominiquehausser** [comment]
When clicking "Absolute gust speed" in options, selection of map is lost and there is a need to click again on Gusts

**Pull request merged**
