### PR TITLE
normalize overlapping average, ie NOAA 0-3, 0-6 and MF 0-1, 0-2

### PR DESCRIPTION
**Pull request by did-g**
Hi
for PRATE and CLOUD
And don't convert average p rate to p tot.
Same formula as wgrip2 so some result, cloud  id not always in 0..100.*

Regards
Didier

NB
fdd39bf28446cba4b7f8cc3a363ffda81cdaa830 breaks Ubuntu Trusty

### CODE REVIEW

**Comment by norulz** [comment]
Hi,
Will this work on both NOAA gribs that have been normalized using wgrib2 -ncep_norm and ALSO on NOAA GFS gribs from other sources that have not been normalized and have the original NOAA accumulation scheme?

**Comment by norulz** [comment]
@did-g Can you please help and see why the travis-ci tests are failing.
Thanks,
David

**Comment by norulz** [comment]
@did-g Looks like I found the fix :-)

**Comment by norulz** [comment]
Another question:
The accumulated precipitation values are displayed as mm/hr but are they not actually mm/per forecast period (which may be 1 hr, 3 hr, 6 hr ...) ??

**Comment by did-g** [comment]
Hi,
this work on both overlapping and not overlapping periods ie:
NOAA 0-3, 0-6, 6-9, 6-12, time series and NOAA normalized  0-3, 3-6, 6-9, 9-12
Or it should, I've tested that zygrib/saildocs grib version 1 not normalized, Xygrib grib2 normalized and NOAAD subsetter output grib2 produce the same result.

Accumulation records are divided by 1/(p2 -p1) ie time interval, caveat currently it's only working if time interval is in hour, I've seen intervals in minutes ( eg 180 rather than 3).

**Comment by norulz** [comment]
Great!

**Pull request merged**
