### PR TITLE
MeteoFrance GRIB downloader + minor changes

### PR DESCRIPTION
**Pull request by theeko74**
I propose the following improvement in XyGrib/zyGrib:
* Add a new GRIB downloader for GRIB files coming from Meteo France. This allows a direct download to both models Arpège (0,1°/5 days) and Arome (0,025°/2 days).

capture d ecran 2018-04-09 a 22 04 54

* Set the standard menu bar for MacOSX (previously menu bar was in the main window, not in finder menu)

capture d ecran 2018-04-09 a 22 05 48

* Remove "dark" skin. I do not see the point of this new skin as the idea of using Qt framework is to look like native OS app. This skin was also not correctly implemented, with many bugs on button, font color, status bar, etc.

* Correct minor issues in pro file for MacOS compilation

### CODE REVIEW

**Comment by norulz** [comment]
Hi Theeko,

Thanks for joining in. 
Unfortunately I did a commit after you posted this pull request and there are a couple of conflicts that need to be taken care of manually. I'll do that some time tomorrow.

We are preparing a grib subset server for on-the-fly subsets of GFS grib2, ICON, Arpege global models and aslo for ICON-EU and NAM.

Have not given too much thought to also integrate sources of pre-cut and packaged gribs. It is also a possibility.

Skin color. Debatable. The current look of the application needs a serious face lift - dark or light. 
(I did BTW make a lot of fixes to the dark skin in the last commit and it is looking much better).

Can you please drop me a mail to opengribs at gmail 
David

**Comment by theeko74** [comment]
Hi Norulz,

Thanks for your reply.
I've resolved the conflicts for merging.

About the new skin, I agree, zyGrib needs a serious lifting ;-) Bug I think before changing to "dark" skin is a user choose (some people like, other don't). So maybe the way to go is to make it activable/disable in options?

**Comment by dominiquehausser** [comment]
Skin color : one advantage with the dark skin is when working at night on a boat has a less negative effect on night vision.
But if it not too complicated to have the opportunity of choosing (really not a priority)...

Skin lifting : this will be an eternal debate, as taste and colours are quite personal.

One important thing is the colour scale (even if this was not completely standard in zyGrib, zyGrib users have get use to it (after so many years). It can be adapted (but this will need an explanation) and is important that if change units, the scale remain the same - meaning that 10 knots ~ 20 km/h ~ 5 m/s.
I suggest m/s is the base (as it is the case for meteorologist) and other units are adapted using at least 1 decimal in the scale's numbers.

Just a light comment about comparison : I do it since a long time opening twice or more zyGrib (that allow me also to have the info at surface and 500 hPa or 2 different models). One advantage having 2 grib files open in the same instance is to have for instance wind and waves/currents coming from 2 different sources or 2 differents scale (synoptic and local for some area).

**Comment by theeko74** [comment]
I think dark theme is a good idea, why not, but should be implemented first as an option (so it lets time for developer to make it nice), and then after a while it will become the default theme.

**Pull request merged**
