### PR TITLE
Accumulation time range use the right unit

### PR DESCRIPTION
**Pull request by did-g**
Hi

P1 an P2 are in unitOfTimeRange unit, convert them to hour when computing.

Need testing but it should solve accumulation issue.

### CODE REVIEW

**Comment by norulz** [comment]
Hi,
Something is wrong. I tested with a grib2 file and it is OK but with grib1 the precipitation values are too small by a factor of about 14.
I have attached 2 identical grib files, one is grib1 and one is grib2. Check for Wed 23/12 1800z at POI 32° 5.82' N 034° 40.24' E.
The value of 7.24 mm/h is the correct one.

[2012220000_f000000_arw_d01.zip](https://github.com/opengribs/XyGrib/files/5743080/2012220000_f000000_arw_d01.zip)
[Crusade_12km_WRF_WAM_201222-00.zip](https://github.com/opengribs/XyGrib/files/5743082/Crusade_12km_WRF_WAM_201222-00.zip)

**Comment by norulz** [comment]
I updated the correct precipitation value NOT 7.24 but 2.42 mm/hr :-)

**Comment by did-g** [comment]
I'm not following here, it seems ok to me.
Am I missing something?

**Comment by norulz** [comment]
Hi,
Are you getting the same rates of precipitation in both of the grib files?
The grib1 file was converted from the grib2.
In 1.2.6 both show the same rate for 3 hours without correction for 1 hour of precipitation.
In 1.2.;7 before the last PR the grib2 file was corrected for hourly rate but the grib1 was still showing accumulation for 3hours.
In 1.2.7 after the last PR the grib2 file is OK but the grib1 shows very low values of precipitation. It appears that the rate calculation is being overly applied.

**Pull request merged**
