### PR TITLE
Average, accumulation compute not hourly period of time

### PR DESCRIPTION
**Pull request by did-g**
Hi,
should help with
 
https://github.com/opengribs/XyGrib/issues/262

### CODE REVIEW

**Comment by norulz** [comment]
I tried the fix and it appear to be OK.
I only tried it with the particular grib where I noticed the issue.

**Comment by norulz** [comment]
Hi @did-g 

It works for grib2 but not for grib1. 
I've attached a grib1 fileb
[apcp_ver1.zip](https://github.com/opengribs/XyGrib/files/5734689/apcp_ver1.zip)

**Comment by norulz** [comment]
Hi @did-g 

It works for grib2 but not for grib1. 
[apcp_ver1.zip](https://github.com/opengribs/XyGrib/files/5739615/apcp_ver1.zip)

I've attached a grib1 fileb

**Comment by did-g** [comment]
Thanks, I'll fix it.

**Pull request merged**
