### PR TITLE
Sea temperature

### PR DESCRIPTION
**Pull request by did-g**
Hi,
fix a couple of small bugs and add sea tempeature with it's own colormap in Sea Menu.
Tested with saildoc GRIB1 RTOFS and NAM GRIB2 (whole set from NOAA).

Notes:
- colormap isn't very good.
- Use land mask if available?

Regards
Didier

### CODE REVIEW

**Comment by dominiquehausser** [comment]
Great...
XygribWaterTemp_RTOFS

**Comment by norulz** [comment]
Salut!

**Comment by norulz** [comment]
Hi,
I tried rtgsst data from NOAA at ftp://ftp.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/sst.20191107/
and found that I can get a value of the sea temp in the Weather Data table which appears in the regular "Temperature(sfc) box but not in the Sea Temp. box. In addition the "Water Temperature" option under "Sea" is not active and the values do not show in the MeteoTable.
It looks like an issue of correctly identifying the NOAA SST grib as sea data.

**Comment by did-g** [comment]
What should be the Id, NOAA_NCEP_SST or NOAA_GFS?

**Pull request merged**
